const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs');
(async()=>{const b=await chromium.launch({headless:true,channel:'msedge'});try{
const p=await b.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.clock.install({time:new Date('2026-09-13T12:00:00Z')});await p.clock.pauseAt(new Date('2026-09-13T12:00:01Z'));await p.goto('http://127.0.0.1:4174');await require('./test-start.cjs')(p);
async function setup(k='betta',q=1,two=false){await p.evaluate(({k,q,two})=>{shopEditor.begin();Object.assign(state,{level:3,money:10000,speed:1,employee:two?'eva':null,employeeUnpaid:false,wageElapsed:0,served:0,kitRequested:false,orders:[],stock:Object.fromEntries(Object.keys(products).map(x=>[x,x===k?q:0])),logistics:{version:1,bins:{[k==='betta'?'betta-1':'shelf-1']:{[k]:q}}},shelf:true,tank3:true,sold:{}});state.moments={version:1,cooldown:999999,sequence:0};state.layout=ShopLayout.create();for(const o of state.layout.objects)if(['shelf','tank3'].includes(o.kind))o.placed=true;Math.random=()=>0;window.dispatchEvent(new Event('layoutchange'));shopEditor.end();}, {k,q,two})}
async function invariant(){return p.evaluate(()=>{for(const k of Object.keys(products)){const sum=ShopLogistics.stored(k)+ShopLogistics.exposed(k)+ShopLogistics.transported(k);if(sum!==state.stock[k])throw Error('Ledger '+k);if(ShopLogistics.transported(k)<0)throw Error('Negative transport')}const g=ShopNavigation.build(state.layout,state).grids.main;for(const w of ShopStaff.snapshot())if(!ShopNavigation.clear(g,w.position))throw Error('Worker collision');return ShopStaff.snapshot()})}
async function until(predicate,limit=240){for(let i=0;i<limit;i++){await p.clock.runFor(250);await invariant();if(await p.evaluate(predicate))return}throw Error('Timeout '+predicate.toString())}
async function reloadExact(){await p.evaluate(()=>saveGame(false));const before=await p.evaluate(()=>({stock:state.stock,logistics:state.logistics,session:state.serviceSession,money:state.money}));await p.reload();assert.deepEqual(await p.evaluate(()=>({stock:state.stock,logistics:state.logistics,session:shopCirculation.serialize(),money:state.money})),before);await invariant()}
for(const k of ['betta','food']){
 await setup(k);await until(()=>ShopStaff.snapshot().some(w=>w.phase.startsWith('preparing')));
 assert.equal(await p.evaluate(k=>ShopLogistics.exposed(k),k),1);assert.equal(await p.evaluate(k=>ShopLogistics.transported(k),k),0);await reloadExact();
 await until(()=>ShopStaff.snapshot().some(w=>w.phase==='carrying-order'));
 const picked=await p.evaluate(k=>({total:state.stock[k],exposed:ShopLogistics.exposed(k),stored:ShopLogistics.stored(k),transported:ShopLogistics.transported(k),records:state.logistics.transports,worker:ShopStaff.snapshot().find(w=>w.job!==null)}),k);
 assert.equal(picked.total,1);assert.equal(picked.exposed,0);assert.equal(picked.stored,0);assert.equal(picked.transported,1);assert.equal(picked.records[picked.worker.transportId].items[0].k,k);
 assert.ok(await p.locator('.live-worker .purchase-bag').first().isVisible());await reloadExact();
 await until(()=>ShopStaff.snapshot().some(w=>w.phase==='checkout'));await reloadExact();
 await until(()=>state.served===1);assert.equal(await p.evaluate(k=>state.stock[k],k),0);assert.equal(await p.evaluate(k=>ShopLogistics.transported(k),k),0);await reloadExact();await p.clock.runFor(15000);assert.equal(await p.evaluate(()=>state.served),1);await invariant();console.log('PASS pickup/payment/reloads',k);
}
await setup();await until(()=>ShopStaff.snapshot().some(w=>w.phase==='carrying-order'));await p.evaluate(()=>{shopEditor.begin();shopEditor.end();saveGame(false)});assert.equal(await p.evaluate(()=>state.stock.betta),1);assert.equal(await p.evaluate(()=>ShopLogistics.at('betta-1','betta')),1);assert.equal(await p.evaluate(()=>ShopLogistics.transported('betta')),0);await p.reload();await invariant();console.log('PASS editor returns once');
await setup();await until(()=>ShopStaff.snapshot().some(w=>w.phase==='carrying-order'));await p.evaluate(()=>{saveGame(false);const s=JSON.parse(localStorage.getItem('aquariumShopV01'));s.serviceSession.signature='invalid';localStorage.setItem('aquariumShopV01',JSON.stringify(s));resetting=true});await p.reload();assert.equal(await p.evaluate(()=>ShopLogistics.transported('betta')),0);assert.equal(await p.evaluate(()=>ShopLogistics.at('betta-1','betta')),1);await p.reload();await invariant();assert.equal(await p.evaluate(()=>state.stock.betta),1);console.log('PASS invalid session returns cargo once');
await setup();await until(()=>ShopStaff.snapshot().some(w=>w.phase==='carrying-order'));await p.evaluate(()=>{saveGame(false);const s=JSON.parse(localStorage.getItem('aquariumShopV01'));s.layout.objects.find(o=>o.id==='betta-1').placed=false;localStorage.setItem('aquariumShopV01',JSON.stringify(s));resetting=true});await p.reload();assert.equal(await p.evaluate(()=>ShopLogistics.stored('betta')),1);assert.equal(await p.evaluate(()=>ShopLogistics.transported('betta')),0);console.log('PASS missing origin returns to receiving');
await setup('betta',1,true);await until(()=>state.served===1);await p.clock.runFor(20000);assert.equal(await p.evaluate(()=>state.served),1);await invariant();console.log('PASS two workers compete for last fish');
await setup('betta',6,true);let parallel=false;for(let i=0;i<360;i++){await p.clock.runFor(250);const ws=await invariant();if(ws.filter(w=>w.transportId).length===2){parallel=true;await reloadExact();break}}assert.ok(parallel,'two independent sale bags');await until(()=>state.served>=2);await invariant();console.log('PASS concurrent sale bags and restore');
assert.deepEqual(errors,[]);fs.writeFileSync('cargo-sales-report.json',JSON.stringify({fish:true,goods:true,reloadPhases:['preparing','carrying-order','checkout','paid'],editor:true,invalidSession:true,missingOrigin:true,lastFish:true,twoBags:true,errors},null,2));
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
