
const products={betta:{name:'Betta',buy:25,sell:45,vol:0},comet:{name:'Cometa',buy:15,sell:30,vol:0},food:{name:'Comida básica',buy:20,sell:35,vol:1}};
let state={money:500,level:1,served:0,capacity:20,stock:{betta:5,comet:6,food:5},shelf:false,tank3:false,warehouse:false,lastSeen:Date.now(),delivery:null,restocked:0};
const $=id=>document.getElementById(id);const fmt=n=>Math.floor(n).toLocaleString('es-ES');
function used(){return Object.entries(state.stock).reduce((a,[k,v])=>a+v*products[k].vol,0)}
function log(t,c=''){let d=document.createElement('div');d.className=c;d.textContent='• '+t;$('log').prepend(d);while($('log').children.length>80)$('log').lastChild.remove();window.dispatchEvent(new CustomEvent('notice',{detail:t}))}
function render(){ $('money').textContent=fmt(state.money);$('level').textContent=state.level;$('served').textContent=state.served;$('capacity').textContent=state.capacity;$('used').textContent=used();$('stock').innerHTML=Object.entries(products).map(([k,p])=>`<div class="stockline"><span>${p.name}</span><b>${state.stock[k]||0}</b></div>`).join('');$('shelfBtn').disabled=state.shelf;$('tankBtn').disabled=!state.shelf||state.tank3;$('warehouseBtn').disabled=state.level<8||state.warehouse;$('tank3').style.display=state.tank3?'block':'none';window.dispatchEvent(new Event('statechange'));}
function recalcLevel(){let s=state.served;state.level=Math.min(10,1+(s>=5)+(s>=10)+(s>=18)+(s>=28)+(s>=40)+(s>=55)+(s>=75)+(s>=100)+(s>=130));}
function customer(){let keys=Object.keys(products).filter(k=>(state.stock[k]||0)>0);if(!keys.length){log('Cliente se fue: no había stock','warn');return}let k=keys[Math.floor(Math.random()*keys.length)],p=products[k];state.stock[k]--;state.money+=p.sell;state.served++;window.dispatchEvent(new CustomEvent('sale',{detail:p.sell}));log(`Venta: ${p.name} +${p.sell} 🪙`,'good');recalcLevel();render();saveGame(false)}
function order(k,q){if(!Object.hasOwn(products,k)||![1,5].includes(q)){log('Pedido no válido','warn');return}if(state.delivery){log('Ya hay una entrega en camino','warn');return}let p=products[k],cost=p.buy*q;if(state.money<cost){log('No tienes suficiente dinero','warn');return}if(used()+p.vol*q>state.capacity){log('No cabe en el almacén','warn');return}state.money-=cost;state.delivery={k,q,end:Date.now()+30000};log(`Pedido realizado: ${q} ${p.name}. Entrega 30 s`);render();saveGame(false)}
function deliveryTick(){if(!state.delivery){$('delivery').textContent='';return}let left=Math.max(0,state.delivery.end-Date.now());$('delivery').textContent='Entrega en '+Math.ceil(left/1000)+' s';if(left<=0){let d=state.delivery;state.stock[d.k]=(state.stock[d.k]||0)+d.q;log(`Pedido recibido: ${d.q} ${products[d.k].name}`,'good');state.delivery=null;state.restocked=(state.restocked||0)+1;render();saveGame(false)}}
function upgradeShelf(){if(state.shelf)return;if(state.money<250)return log('Faltan monedas','warn');state.money-=250;state.shelf=true;log('¡Primera estantería instalada!','good');render();saveGame(false)}
function upgradeTank(){if(!state.shelf||state.tank3)return;if(state.money<350)return log('Faltan monedas','warn');state.money-=350;state.tank3=true;log('¡Tercer acuario construido!','good');render();saveGame(false)}
function upgradeWarehouse(){if(state.level<8||state.warehouse)return;if(state.money<4000)return log('Faltan monedas','warn');state.money-=4000;state.capacity=50;state.warehouse=true;log('¡Almacén ampliado a 50!','good');render();saveGame(false)}
let resetting=false;
function saveGame(show=true){if(resetting)return;state.lastSeen=Date.now();try{localStorage.setItem('aquariumShopV01',JSON.stringify(state))}catch(e){if(show)log('No se ha podido guardar en este navegador','warn');return}if(show)log('Partida guardada','good')}
function load(){try{let raw=localStorage.getItem('aquariumShopV01');if(!raw)return;let old=JSON.parse(raw),hours=Math.min(4,(Date.now()-(old.lastSeen||Date.now()))/3600000);state={...state,...old};if(hours>.02){let bonus=Math.floor(hours*250*.7);state.money+=bonus;log(`Mientras estabas fuera: +${bonus} 🪙 (${hours.toFixed(1)} h)`,'good')}}catch(e){}}
function resetGame(){if(confirm('¿Reiniciar el prototipo?')){resetting=true;localStorage.removeItem('aquariumShopV01');location.reload()}}
load();render();log('Tienda abierta. Primer objetivo: vender y reinvertir.');setInterval(customer,8000);setInterval(deliveryTick,250);setInterval(()=>saveGame(false),5000);
