// New features use message keys; legacy management copy remains in Spanish.
window.ShopI18n=(()=>{
const messages={
es:{customize:'Personalizar mi tienda',saveIdentity:'Guardar identidad',back:'Volver sin cambiar',welcome:'Tu pequeña tienda, a tu manera',intro:'Ponle nombre y elige su emblema. Tu historia empieza aquí.',name:'Nombre de la tienda',color:'Color de la tienda',symbol:'Símbolo',shape:'Forma',start:'Abrir mi tienda',language:'Idioma de la identidad',identity:'Identidad de tu tienda',defaultName:'Mi tienda acuática',tagline:'Acuarios y pequeños descubrimientos',fish:'Pez',betta:'Betta',plant:'Planta',coral:'Coral',bubbles:'Burbujas',wave:'Ola',initials:'Iniciales',circle:'Círculo',soft:'Cuadrado suave',plain:'Sin fondo',sage:'Salvia',ocean:'Océano',terracotta:'Terracota',plum:'Ciruela',gold:'Miel',preview:'Vista previa del rótulo',nameRequired:'Escribe un nombre para tu tienda.',open:'ABIERTO',saved:'La identidad se guardará con tu partida.',legacy:'Tu tienda de siempre conserva su progreso.',identityHelp:'El nombre, el emblema y los colores acompañan a tu tienda.',languageHelp:'Los textos nuevos de identidad están disponibles en español e inglés. La gestión conserva por ahora sus textos en español.',hello:'¡Hola!',look:'Voy a mirar',order:'Mi encargo',aquarium:'Mi acuario',seeking:'Busco {name}',set:'El conjunto',queue:'A la cola',till:'A la caja',turn:'Mi turno…',pay:'Voy a pagar',myTurn:'¡Me toca!',checkout:'En caja',thanks:'¡Gracias!',bye:'Hasta luego',later:'Otra vez será',blocked:'Sin paso',bag:'Compra preparada',clerk:'Dependiente',nameHelp:'Hasta 28 caracteres. Puedes usar espacios y acentos.'},
en:{customize:'Personalise my shop',saveIdentity:'Save identity',back:'Back without changes',welcome:'Your little shop, your own way',intro:'Give it a name and choose an emblem. Your story begins here.',name:'Shop name',color:'Shop colour',symbol:'Symbol',shape:'Shape',start:'Open my shop',language:'Identity language',identity:'Your shop identity',defaultName:'My aquarium shop',tagline:'Aquariums and little discoveries',fish:'Fish',betta:'Betta',plant:'Plant',coral:'Coral',bubbles:'Bubbles',wave:'Wave',initials:'Initials',circle:'Circle',soft:'Soft square',plain:'No background',sage:'Sage',ocean:'Ocean',terracotta:'Terracotta',plum:'Plum',gold:'Honey',preview:'Shop sign preview',nameRequired:'Enter a name for your shop.',open:'OPEN',saved:'Your identity will be saved with your game.',legacy:'Your existing shop keeps all its progress.',identityHelp:'Your name, emblem and colours belong to your shop.',languageHelp:'New identity text is available in Spanish and English. Management text is currently in Spanish.',hello:'Hello!',look:'Just browsing',order:'My order',aquarium:'My aquarium',seeking:'Seeking {name}',set:'The whole set',queue:'To the queue',till:'To the till',turn:'My turn…',pay:'Ready to pay',myTurn:'My turn!',checkout:'At the till',thanks:'Thank you!',bye:'Goodbye',later:'Maybe next time',blocked:'No way through',bag:'Purchase ready',clerk:'Shop assistant',nameHelp:'Up to 28 characters. Spaces and accents are welcome.'}
};
let locale='es';
return {messages,get locale(){return locale},set(value){locale=value==='en'?'en':'es';document.documentElement.lang=locale},t(key,params={}){return (messages[locale][key]||messages.es[key]||key).replace(/\{(\w+)\}/g,(_,k)=>params[k]??'')}};
})();
