const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
const p=await browser.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.clock.install({time:new Date('2026-09-11T12:00:00Z')});await p.clock.pauseAt(new Date('2026-09-11T12:00:01Z'));await p.goto('http://127.0.0.1:4174');await require('./test-start.cjs')(p);
async function setup(two=false,blocked=false,far=false){await p.evaluate(({two,blocked,far})=>{
shopEditor.begin();Object.assign(state,{level:two?9:3,speed:1,money:100000,employee:two?'eva':null,employeeUnpaid:false,wagesPaid:0,wageElapsed:0,orders:[],orderSerial:0,served:0,sold:{},kitRequested:false,shelf:true,expansion:far,stock:Object.fromEntries(Object.keys(products).map(k=>[k,0])),logistics:{version:1,bins:{}},restocked:0});
Object.assign(state.moments,{active:null,request:null,offer:null,interest:null,cooldown:999999});state.layout=ShopLayout.create();if(far){state.layout.rooms[0].width=18;state.layout.rooms[0].depth=16;Object.assign(state.layout.objects.find(o=>o.kind==='warehouse'),{x:15,y:13})}
if(blocked)state.layout.rooms[0].obstacles=[{x:12,y:5,width:4,depth:1},{x:12,y:8,width:4,depth:1},{x:12,y:6,width:1,depth:2},{x:15,y:6,width:1,depth:2}];
window.dispatchEvent(new Event('layoutchange'));render();shopEditor.end();window.seenPhases=[];window.peak=0;
}, {two,blocked,far})}
async function tick(ms){await p.clock.runFor(ms);return p.evaluate(()=>{const ws=ShopStaff.snapshot(),g=ShopNavigation.build(state.layout,state).grids.main;for(const w of ws){if(!ShopNavigation.clear(g,w.position))throw Error('Employee inside obstacle');if(w.motion&&!w.motion.every((x,i)=>!i||ShopNavigation.segmentClear(g,w.motion[i-1],x)))throw Error('Path crosses obstacle');if(!seenPhases.includes(w.phase))seenPhases.push(w.phase)}const jobs=ws.filter(w=>w.restock);peak=Math.max(peak,jobs.length);if(new Set(jobs.map(w=>w.restock.objectId+':'+w.restock.k)).size!==jobs.length)throw Error('Duplicate restock');for(const k of Object.keys(products)){if(ShopLogistics.exposed(k)+ShopLogistics.transported(k)+ShopLogistics.stored(k)!==state.stock[k]||ShopLogistics.stored(k)<0)throw Error('Invalid location ledger');const delivered=state.orders.filter(o=>o.status==='delivered'&&o.k===k).reduce((s,o)=>s+o.q,0);if(state.stock[k]+(state.sold[k]||0)!==delivered)throw Error('Conservation failed '+k)}return {ws,stock:state.stock,exposed:Object.fromEntries(Object.keys(products).map(k=>[k,ShopLogistics.exposed(k)])),served:state.served,phases:seenPhases,peak};})}
await setup(true);await p.evaluate(()=>{order('betta',5);order('comet',5);order('food',5)});await tick(30000);assert.equal(await p.evaluate(()=>state.restocked),3);assert.equal(await p.evaluate(()=>Object.values(state.logistics.bins).flatMap(Object.values).reduce((s,n)=>s+n,0)),0,'arrivals stay in reception');assert.ok(await p.locator('.received-fish').count());assert.ok(await p.locator('.received-box').count());
const saves=[];let outcome;for(let i=0;i<240;i++){outcome=await tick(500);for(const phase of ['to-receipt','collecting-stock','carrying-stock','restocking']){if(!saves.includes(phase)&&outcome.ws.some(w=>w.phase===phase)){await p.evaluate(()=>saveGame(false));const before=await p.evaluate(()=>({stock:state.stock,logistics:state.logistics,session:state.serviceSession,orders:state.orders}));await p.reload();const after=await p.evaluate(()=>({stock:state.stock,logistics:state.logistics,session:state.serviceSession,orders:state.orders}));assert.deepEqual(after,before,'reload '+phase);saves.push(phase);await p.screenshot({path:__dirname+'/v011-'+phase+'.png',fullPage:true});await p.evaluate(({phases,peak})=>{window.seenPhases=phases;window.peak=peak},outcome)}}if(saves.length===4&&outcome.served>=5)break}
assert.equal(saves.length,4);assert.equal(outcome.peak,2);assert.ok(outcome.served>0);await p.screenshot({path:__dirname+'/v011-mobile.png',fullPage:true});
await setup(false,true);await p.evaluate(()=>order('betta',5));await tick(65000);assert.equal(await p.evaluate(()=>ShopLogistics.exposed('betta')),0);assert.equal(await p.evaluate(()=>state.stock.betta),5);assert.ok(await p.locator('#accessAlert').isVisible());await p.evaluate(()=>{shopEditor.begin();state.layout.rooms[0].obstacles=[];window.dispatchEvent(new Event('layoutchange'));shopEditor.end()});let reopened;for(let i=0;i<80;i++){reopened=await tick(500);if(reopened.served)break}assert.ok(reopened.served>0,'reopening restores replenishment');
async function distance(far){await setup(false,false,far);await p.evaluate(()=>order('betta',5));await tick(30000);for(let i=0;i<300;i++){const a=await tick(100);if(a.exposed.betta)return {time:(i+1)/10,distance:a.ws[0].distance}}throw Error('No replenishment')}
const near=await distance(false),far=await distance(true);assert.ok(far.time>near.time);assert.ok(far.distance>near.distance);
// Editing cancels a carrying task without changing ownership; next task completes it.
await setup(false);await p.evaluate(()=>order('betta',5));await tick(30000);for(let i=0;i<100;i++){const a=await tick(100);if(a.ws.some(w=>w.phase==='carrying-stock'))break}const before=await p.evaluate(()=>state.stock.betta);await p.evaluate(()=>{shopEditor.begin();shopEditor.end();saveGame(false)});await p.reload();await p.evaluate(()=>{window.seenPhases=[];window.peak=0});await tick(30000);assert.equal(await p.evaluate(()=>state.stock.betta+(state.sold.betta||0)),before);
// One-tile passage between reception and display uses real collision geometry.
await setup(false,false,true);await p.evaluate(()=>{shopEditor.begin();state.layout.rooms[0].obstacles=[{x:13,y:0,width:1,depth:7},{x:13,y:8,width:1,depth:8}];window.dispatchEvent(new Event('layoutchange'));shopEditor.end();order('betta',5)});await tick(30000);let narrow=false;for(let i=0;i<200;i++){const a=await tick(250);if(a.exposed.betta){narrow=true;break}}assert.ok(narrow);await p.screenshot({path:__dirname+'/v011-narrow.png',fullPage:true});
for(const width of [320,390,768,1280]){await p.setViewportSize({width,height:900});await p.evaluate(()=>showPanel('stock'));assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:__dirname+'/v011-receiving-'+width+'.png',fullPage:true});await p.locator('#closePanel').click()}
assert.deepEqual(errors,[]);fs.writeFileSync('logistics-v011-report.json',JSON.stringify({simultaneousArrivals:3,saves,twoWorkers:outcome.peak,sales:outcome.served,blockedAndReopened:true,near,far,interruptedTransfer:true,narrowPassage:true,responsive:[320,390,768,1280],errors},null,2));console.log('PASS logistics',JSON.stringify({saves,near,far,peak:outcome.peak,sales:outcome.served}));
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
