const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const b=await chromium.launch({headless:true,channel:'msedge'});try{
let p=await b.newPage({viewport:{width:390,height:844}});const errors=[];const prepare=async(page,date)=>{page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>window.addEventListener('load',()=>window.dispatchEvent(new Event('editbegin'))));await page.clock.install({time:new Date(date)});await page.clock.pauseAt(new Date(new Date(date).getTime()+1000));await page.goto('http://127.0.0.1:4174')};
await prepare(p,'2026-09-09T12:00:00Z');await require('./test-start.cjs')(p);
await p.evaluate(()=>{window.dispatchEvent(new Event('editbegin'));Object.assign(state,{level:7,money:10000,speed:1,orders:[],orderSerial:0,stock:Object.fromEntries(Object.keys(products).map(k=>[k,0]))});render();showPanel('stock')});
for(const k of ['betta','food','guppy','filter']){assert.ok(await p.locator('[data-order="'+k+'"]').isEnabled());await p.locator('[data-order="'+k+'"]').click()}
let orders=await p.evaluate(()=>incomingOrders());assert.equal(orders.length,4);assert.ok(orders.every(o=>o.remaining===30000&&o.cost>0&&o.orderedAt&&o.status==='in_transit'&&o.deliveredAt===null));assert.equal(new Set(orders.map(o=>o.id)).size,4);
assert.equal(await p.evaluate(()=>reservedSpace()),15);await p.clock.runFor(10000);assert.deepEqual(await p.evaluate(()=>incomingOrders().map(o=>o.remaining)),[20000,20000,20000,20000]);
await p.locator('[data-order="food"]').click();assert.equal(await p.evaluate(()=>reservedSpace()),20);
await p.locator('[data-quantity="1"]').click();assert.equal(await p.locator('[data-order="filter"]').isEnabled(),false);const money=await p.evaluate(()=>state.money);await p.evaluate(()=>order('filter',1));assert.equal(await p.evaluate(()=>state.money),money);assert.equal(await p.evaluate(()=>incomingOrders().length),5);
await p.locator('[data-quantity="5"]').click();assert.ok(await p.locator('[data-order="betta"]').isEnabled());await p.locator('[data-order="betta"]').click();assert.equal(await p.evaluate(()=>reservedSpace()),20,'fish preserve current separate vol=0 behaviour');
await p.locator('#incomingOrders').scrollIntoViewIfNeeded();await p.screenshot({path:__dirname+'/v081-incoming-mobile.png',fullPage:true});await p.setViewportSize({width:1280,height:900});await p.screenshot({path:__dirname+'/v081-incoming-desktop.png',fullPage:true});
await p.evaluate(()=>saveGame(false));const before=await p.evaluate(()=>({orders:state.orders,money:state.money,identity:state.identity,layout:state.layout}));await p.reload();assert.deepEqual(await p.evaluate(()=>({orders:state.orders,money:state.money,identity:state.identity,layout:state.layout})),before);assert.equal(await p.evaluate(()=>reservedSpace()),20);
await p.clock.runFor(20000);assert.equal(await p.evaluate(()=>incomingOrders().length),2);assert.deepEqual(await p.evaluate(()=>({food:state.stock.food,filter:state.stock.filter,betta:state.stock.betta,guppy:state.stock.guppy,used:used(),reserved:reservedSpace()})),{food:5,filter:5,betta:5,guppy:5,used:15,reserved:5});
assert.deepEqual(await p.evaluate(()=>incomingOrders().map(o=>o.remaining)),[10000,10000]);await p.clock.runFor(10000);
assert.equal(await p.evaluate(()=>incomingOrders().length),0);assert.equal(await p.evaluate(()=>used()),20);assert.equal(await p.evaluate(()=>state.restocked),6);assert.equal(await p.evaluate(()=>state.xp),120);
const complete=await p.evaluate(()=>({stock:state.stock,xp:state.xp,received:state.restocked}));await p.reload();await p.clock.runFor(1000);assert.deepEqual(await p.evaluate(()=>({stock:state.stock,xp:state.xp,received:state.restocked})),complete);
// Different suppliers advance together; closing and reopening does not consume offline time.
await p.evaluate(()=>{order('betta',1);state.supplier='wholesale';order('comet',10);render()});assert.deepEqual(await p.evaluate(()=>incomingOrders().map(o=>o.remaining)),[30000,90000]);
await p.clock.runFor(30000);assert.equal(await p.evaluate(()=>incomingOrders()[0].remaining),60000);assert.equal(await p.evaluate(()=>state.stock.comet),0);await p.evaluate(()=>saveGame(false));
const disk=await p.context().storageState(),transit=await p.evaluate(()=>incomingOrders());await p.context().close();
const context=await b.newContext({storageState:disk,viewport:{width:390,height:844}});p=await context.newPage();await prepare(p,'2026-09-10T12:00:00Z');assert.deepEqual(await p.evaluate(()=>incomingOrders()),transit);
await p.clock.runFor(59000);assert.equal(await p.evaluate(()=>state.stock.comet),0);await p.clock.runFor(1000);assert.equal(await p.evaluate(()=>state.stock.comet),10);assert.equal(await p.evaluate(()=>state.supplierReceived.wholesale),1);
assert.ok(await p.evaluate(()=>state.orders.every(o=>o.status==='delivered'&&o.remaining===0&&o.deliveredAt>=o.orderedAt)));
// A v0.8 single paid delivery migrates without charging again or skipping its timer.
const legacyMoney=await p.evaluate(()=>{const legacy={...state};delete legacy.orders;delete legacy.ordersVersion;delete legacy.orderSerial;legacy.stock={...state.stock,food:0,filter:0,conditioner:0};legacy.delivery={k:'conditioner',q:1,remaining:17500,end:Date.now()+17500,supplier:'local'};resetting=true;localStorage.setItem('aquariumShopV01',JSON.stringify(legacy));return legacy.money});
await p.reload();assert.equal(await p.evaluate(()=>state.money),legacyMoney);assert.equal(await p.evaluate(()=>incomingOrders()[0].remaining),17500);assert.equal(await p.evaluate(()=>reservedSpace()),1);await p.clock.runFor(17500);assert.equal(await p.evaluate(()=>state.stock.conditioner),1);await p.reload();await p.clock.runFor(20000);assert.equal(await p.evaluate(()=>state.stock.conditioner),1);
await p.evaluate(()=>{ShopI18n.set('en');updateShopStatus();showPanel('stock')});assert.equal(await p.locator('#incomingTitle').textContent(),'Orders on the way');
for(const width of [320,390,768,1280]){await p.setViewportSize({width,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))}
assert.deepEqual(errors,[]);fs.writeFileSync(__dirname+'/orders-v081-report.json',JSON.stringify({simultaneousOrders:6,localSeconds:30,wholesaleSeconds:90,reservedCapacity:20,staggeredDeliveries:true,reload:true,closedAndRestoredNextDay:true,legacyMigration:true,noDoubleCredit:true,localization:true,errors},null,2));console.log('PASS: UI simultaneous orders, atomic capacity reservation, stock/cost, independent arrivals, different suppliers, save/reload/next-day reopen, migration and exactly-once delivery.');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
