// Pure emergency policy. Active real seconds, not accelerated game time or wall-clock dates.
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ShopRecoveryModel=api})(globalThis,()=>{
function normalize(raw={}){const n=(x,d=0)=>Number.isFinite(x)&&x>=0?x:d;return {version:1,active:n(raw.active),progress:n(raw.progress),totalAid:n(raw.totalAid),totalRewards:n(raw.totalRewards),nextReward:n(raw.nextReward),windowStart:n(raw.windowStart),windowCount:Math.floor(n(raw.windowCount)),serial:Math.floor(n(raw.serial)),pending:null}}
function usable(k,state,catalog){return ['betta','comet','food','conditioner'].includes(k)||!!state[catalog[k]?.display]}
function resources(state,catalog){let n=Math.max(0,state.money||0);for(const [k,p] of Object.entries(catalog))if(usable(k,state,catalog)){n+=Math.max(0,state.stock[k]||0)*p.buy;for(const o of state.orders||[])if(o.k===k&&o.status==='in_transit')n+=o.q*p.buy}return n}
function windowReset(r,c){if(r.active-r.windowStart>=c.rewardWindow){r.windowStart=r.active;r.windowCount=0}}
function tick(state,catalog,c,dt){if(!Number.isFinite(dt)||dt<=0)return 0;const r=state.recovery;r.active+=dt;windowReset(r,c);const need=Math.max(0,c.target-resources(state,catalog));if(!need){r.progress=0;return 0}r.progress+=dt;const periods=Math.floor(r.progress/c.coinInterval),amount=Math.min(need,periods*c.coinAmount);if(periods)r.progress-=periods*c.coinInterval;if(amount){state.money+=amount;r.totalAid+=amount}return amount}
function rewardQuote(state,catalog,c){const r=state.recovery;windowReset(r,c);if(r.pending)return {amount:0,reason:'Simulación en curso'};if(r.active<r.nextReward)return {amount:0,reason:'Disponible en '+Math.ceil((r.nextReward-r.active)/60)+' min de juego abierto'};if(r.windowCount>=c.rewardLimit)return {amount:0,reason:'Límite de esta hora alcanzado'};const amount=Math.max(0,Math.min(c.reward,c.rewardResourceCeiling-resources(state,catalog)));return {amount,reason:amount?'':'Reservada para cuando queden pocos recursos'}}
function begin(state,catalog,c){const q=rewardQuote(state,catalog,c);if(!q.amount)return null;const r=state.recovery,id=++r.serial;r.pending={id,amount:q.amount};return id}
function finish(state,catalog,c,id,completed){const r=state.recovery;if(!r.pending||r.pending.id!==id)return 0;const pending=r.pending;r.pending=null;if(!completed)return 0;windowReset(r,c);if(r.active<r.nextReward||r.windowCount>=c.rewardLimit)return 0;const amount=Math.max(0,Math.min(pending.amount,c.rewardResourceCeiling-resources(state,catalog)));if(!amount)return 0;r.nextReward=r.active+c.rewardCooldown;r.windowCount++;r.totalRewards+=amount;state.money+=amount;return amount}
return {normalize,usable,resources,tick,rewardQuote,begin,finish};
});
