const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs');
(async()=>{const b=await chromium.launch({headless:true,channel:'msedge'});try{const p=await b.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.clock.install({time:new Date('2026-09-11T12:00:00Z')});await p.clock.pauseAt(new Date('2026-09-11T12:00:01Z'));await p.goto('http://127.0.0.1:4174');await require('./test-start.cjs')(p);
await p.evaluate(()=>{shopEditor.begin();Object.assign(state,{money:0,level:1,stock:Object.fromEntries(Object.keys(products).map(k=>[k,0])),orders:[],debt:15,speed:12,logistics:{version:1,bins:{}},recovery:ShopRecoveryModel.normalize()});state.moments.cooldown=999999;render()});await p.clock.runFor(30000);assert.equal(await p.evaluate(()=>state.money),0);await p.evaluate(()=>saveGame(false));await p.reload();await p.evaluate(()=>shopEditor.begin());await p.clock.runFor(30000);assert.equal(await p.evaluate(()=>state.money),1,'x12 does not accelerate emergency aid; partial minute survives reload');
await p.evaluate(()=>{ShopRecoveryModel.tick(state,products,ShopDesign.recovery,840);render();shopEditor.end();showPanel('support')});assert.equal(await p.evaluate(()=>state.money),15);assert.ok(await p.locator('#lifelineOrder').isEnabled());await p.screenshot({path:__dirname+'/v011-emergency.png',fullPage:true});await p.locator('#lifelineOrder').click();assert.equal(await p.evaluate(()=>state.money),0);assert.equal(await p.evaluate(()=>incomingOrders().length),1,'level-one player can actually restart');await p.locator('#closePanel').click();await p.evaluate(()=>state.speed=1);for(let i=0;i<100;i++){await p.clock.runFor(1000);if(await p.evaluate(()=>state.served>0))break}assert.ok(await p.evaluate(()=>state.served>0));assert.equal(await p.evaluate(()=>state.debt),0);
await p.evaluate(()=>{shopEditor.begin();state.money=0;state.stock=Object.fromEntries(Object.keys(products).map(k=>[k,0]));state.orders=[];state.recovery=ShopRecoveryModel.normalize();render();showPanel('support')});await p.locator('#rewardStart').click();await p.locator('#rewardCancel').click();assert.equal(await p.evaluate(()=>state.money),0);await p.locator('#rewardStart').click();await p.locator('#rewardComplete').click();assert.equal(await p.evaluate(()=>state.money),10);await p.locator('#rewardComplete').evaluate(b=>b.click());assert.equal(await p.evaluate(()=>state.money),10);await p.evaluate(()=>saveGame(false));await p.reload();await p.evaluate(()=>showPanel('support'));assert.equal(await p.locator('#rewardStart').isEnabled(),false);assert.equal(await p.evaluate(()=>state.money),10);
// Buying strips is optional, paid once, additive to the large upgrade and persistent.
await p.evaluate(()=>{shopEditor.begin();state.level=2;state.money=500;state.microWidth=false;state.microDepth=false;state.expansion=false;state.layout=ShopLayout.create();buyUpgrade('microWidth')});assert.equal(await p.evaluate(()=>state.money),320);assert.equal(await p.evaluate(()=>state.layout.rooms[0].width),17);await p.evaluate(()=>buyUpgrade('microWidth'));assert.equal(await p.evaluate(()=>state.money),320);await p.evaluate(()=>{state.level=3;state.money=500;buyUpgrade('microDepth');shopEditor.end();saveGame(false)});assert.equal(await p.evaluate(()=>state.money),240);const room=await p.evaluate(()=>state.layout.rooms[0]);await p.reload();assert.deepEqual(await p.evaluate(()=>state.layout.rooms[0]),room);
await p.evaluate(()=>{state.level=5;state.served=25;state.kits=1;state.money=1200;buyUpgrade('expansion')});assert.deepEqual(await p.evaluate(()=>({w:state.layout.rooms[0].width,d:state.layout.rooms[0].depth})),{w:21,d:18});await p.evaluate(()=>saveGame(false));await p.reload();assert.equal(await p.evaluate(()=>state.layout.rooms[0].width),21);
for(const width of [320,390,768,1280]){await p.setViewportSize({width,height:900});await p.evaluate(()=>showPanel('support'));assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:__dirname+'/v011-support-'+width+'.png',fullPage:true})}
assert.deepEqual(errors,[]);fs.writeFileSync('recovery-v011-report.json',JSON.stringify({normalTimeAtX12:true,partialMinuteReload:true,zeroMoneyZeroStockRestart:true,debtRepaid:true,rewardCancelled:true,rewardOnce:true,rewardCooldownReload:true,paidStrips:true,expanded:{width:21,depth:18},responsive:true,errors},null,2));console.log('PASS emergency UI, real restart, voluntary reward guards, paid strips and expanded persistence.');}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
