const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs');
(async()=>{const b=await chromium.launch({headless:true,channel:'msedge'});try{const p=await b.newPage({viewport:{width:390,height:844}}),errors=[],reports=[];p.on('pageerror',e=>errors.push(e.message));await p.clock.install({time:new Date('2026-09-11T12:00:00Z')});await p.clock.pauseAt(new Date('2026-09-11T12:00:01Z'));await p.goto('http://127.0.0.1:4174');await require('./test-start.cjs')(p);
// Real frames: project poses back to the grid and verify every movement segment.
await p.evaluate(()=>{const update=ShopCharacters.update;window.audit={samples:0,prev:{},phases:[],maxJobs:0};ShopCharacters.update=(node,pose)=>{update(node,pose);if(!audit.grid)return;const g=audit.grid,dx=(pose.feet.x-g.room.origin.x)/30,dy=(pose.feet.y-g.room.origin.y)/15,pos={x:(dx+dy)/2,y:(dy-dx)/2},id=node.dataset.visitorId;if(!ShopNavigation.clear(g,pos))throw Error('Collision '+id);const prev=audit.prev[id];if(prev&&!ShopNavigation.segmentClear(g,prev,pos))throw Error('Crossing '+id);audit.prev[id]=pos;audit.samples++};});
for(const [name,three,shelf,two] of [['two',false,false,false],['three',true,false,false],['rows',true,true,false],['rotated',true,true,false],['island',true,true,true],['rotated-two',true,true,true]]){
await p.evaluate(({name,three,shelf,two})=>{shopEditor.begin();audit.prev={};audit.phases=[];audit.samples=0;audit.maxJobs=0;Object.assign(state,{level:three?3:2,money:10000,employee:two?'eva':null,employeeUnpaid:false,speed:1,shelf,tank3:three,expansion:false,microWidth:false,microDepth:false,served:0,orders:[],stock:Object.fromEntries(Object.keys(products).map(k=>[k,['betta','comet','guppy','platy'].includes(k)?15:['food','conditioner'].includes(k)?3:0])),logistics:null});state.moments={version:1,cooldown:999999,sequence:0};state.layout=ShopLayout.create();for(const o of state.layout.objects)if(o.kind==='shelf')o.placed=shelf;else if(o.kind==='tank3')o.placed=three;
const changes=name.startsWith('rotated')?{'betta-1':[0,2,90],'comet-1':[4,2,90],'tank-3':[8,2,90]}:name==='island'?{'betta-1':[1,3,0],'comet-1':[8,2,90],'tank-3':[1,9,0],'counter-1':[9,9,0],'shelf-1':[0,0,0],'plant-1':[4,0,0],'plant-3':[0,12,0]}:{};
for(const o of state.layout.objects)if(changes[o.id])[o.x,o.y,o.rotation]=changes[o.id];for(const o of state.layout.objects.filter(o=>ShopLayout.owned(o,state))){const error=ShopLayout.validate(state.layout,o,state);if(error)throw Error(o.id+': '+error)}audit.grid=ShopNavigation.build(state.layout,state).grids.main;window.dispatchEvent(new Event('layoutchange'));render();shopEditor.end();}, {name,three,shelf,two});
for(let i=0;i<120;i++){await p.clock.runFor(500);await p.evaluate(()=>{const ws=ShopStaff.snapshot();for(const w of ws)if(!audit.phases.includes(w.phase))audit.phases.push(w.phase);audit.maxJobs=Math.max(audit.maxJobs,ws.filter(w=>w.job!==null||w.restock).length)})}
const r=await p.evaluate(()=>({sales:state.served,samples:audit.samples,phases:audit.phases,maxJobs:audit.maxJobs,access:ShopNavigation.assess(ShopNavigation.build(state.layout,state)).filter(o=>!o.reachable).map(o=>o.id)}));assert.ok(r.sales>=1,name+' has real sales');assert.deepEqual(r.access,[],name+' accessible');assert.equal(r.maxJobs,two?2:1);reports.push({name,...r});await p.screenshot({path:__dirname+'/v011-'+name+'.png',fullPage:true});console.log('PASS layout',name,r.sales,r.samples);
}
// No magical sale when the display is enclosed.
await p.evaluate(()=>{shopEditor.begin();audit.grid=null;state.stock=Object.fromEntries(Object.keys(products).map(k=>[k,k==='betta'?5:0]));state.logistics=null;state.layout=ShopLayout.create();state.shelf=false;state.tank3=false;state.layout.rooms[0].obstacles=[{x:5,y:2,width:1,depth:3},{x:0,y:5,width:5,depth:1}];window.dispatchEvent(new Event('layoutchange'));shopEditor.end();window.blockedSales=state.served});assert.ok(await p.locator('#accessAlert').isVisible());await p.clock.runFor(30000);assert.equal(await p.evaluate(()=>state.served-blockedSales),0);
assert.deepEqual(errors,[]);fs.writeFileSync('space-staff-v011-report.json',JSON.stringify({reports,blockedNoSale:true,errors},null,2));console.log('PASS space/staff matrix');}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
