const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const b=await chromium.launch({headless:true,channel:'msedge'});try{const p=await b.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.clock.install({time:new Date('2026-09-10T12:00:00Z')});await p.clock.pauseAt(new Date('2026-09-10T12:00:01Z'));await p.goto('http://127.0.0.1:4174');await require('./test-start.cjs')(p);
async function setup(kind){return p.evaluate(kind=>{shopEditor.begin();for(const key of Object.keys(ShopDesign.upgrades))state[key]=false;Object.assign(state,{level:2,money:10000,speed:1,employee:null,employeeUnpaid:false,served:0,xp:0,kits:0,kitRequested:false,orders:[],logistics:null,stock:Object.fromEntries(Object.keys(products).map(k=>[k,k==='betta'?50:0])),expansion:true});Object.assign(state.moments,{active:null,request:null,offer:null,interest:null,cooldown:999999});
const l=ShopLayout.create();l.rooms[0].width=18;l.rooms[0].depth=16;const o=l.objects.find(o=>o.kind==='betta');if(kind==='far')Object.assign(o,{x:1,y:12});if(kind==='narrow') {Object.assign(o,{x:14,y:2,rotation:90});l.rooms[0].obstacles=[{x:13,y:0,width:1,depth:7},{x:13,y:8,width:1,depth:8}]}
state.layout=l;const invalid=l.objects.filter(o=>ShopLayout.owned(o,state)).map(o=>ShopLayout.validate(l,o,state)).filter(Boolean);if(invalid.length)throw Error(invalid.join());render();window.dispatchEvent(new Event('layoutchange'));shopEditor.end();window.caseStart=Date.now();window.lastWorker=null;window.crossed=false;return {start:Date.now(),layout:l};
},kind)}
async function firstSale(){for(let i=0;i<650;i++){await p.clock.runFor(100);const status=await p.evaluate(()=>{const w=ShopStaff.snapshot()[0],g=ShopNavigation.build(state.layout,state).grids.main;if(!ShopNavigation.clear(g,w.position))throw Error('Worker collision');if(window.lastWorker&&!ShopNavigation.segmentClear(g,lastWorker,w.position))throw Error('Worker crossed obstacle');window.lastWorker={...w.position};if(w.position.x>13)window.crossed=true;return {sales:state.served,elapsed:(Date.now()-caseStart)/1000,distance:w.distance,crossed:window.crossed}});if(status.sales)return status}throw Error('No physical sale within 65 game seconds')}
await setup('near');const near=await firstSale();await setup('far');const far=await firstSale();assert.ok(far.distance>near.distance,'far tank requires more worker travel');assert.ok(far.elapsed>near.elapsed,'far tank delays the completed sale');
await setup('narrow');const narrow=await firstSale();assert.ok(narrow.crossed,'employee used the one-tile opening');await p.screenshot({path:__dirname+'/v010-narrow.png',fullPage:true});
await p.evaluate(()=>{shopEditor.begin();state.layout.rooms[0].obstacles.push({x:13,y:7,width:1,depth:1});window.dispatchEvent(new Event('layoutchange'));render()});
const report=await p.evaluate(()=>ShopNavigation.assess(ShopNavigation.build(state.layout,state)).find(o=>o.kind==='betta'));assert.equal(report.reachable,false);assert.equal(await p.locator('#accessAlert').isVisible(),true);await p.locator('#editExit').click();const sold=await p.evaluate(()=>state.served);await p.clock.runFor(45000);assert.equal(await p.evaluate(()=>state.served),sold);
await p.evaluate(()=>{shopEditor.begin();state.layout.rooms[0].obstacles.pop();window.dispatchEvent(new Event('layoutchange'));shopEditor.end()});await p.clock.runFor(45000);assert.ok(await p.evaluate(n=>state.served>n,sold));
await setup('near');await p.evaluate(()=>{state.stock.betta=1;render()});await firstSale();await p.evaluate(()=>saveGame(false));const paid=await p.evaluate(()=>({money:state.money,stock:state.stock,served:state.served,xp:state.xp}));await p.reload();await p.clock.runFor(30000);assert.deepEqual(await p.evaluate(()=>({money:state.money,stock:state.stock,served:state.served,xp:state.xp})),paid,'a paid visitor must not pay twice after reload');
assert.deepEqual(errors,[]);fs.writeFileSync(__dirname+'/staff-distance-v010-report.json',JSON.stringify({near,far,narrow,blockedAndReopened:true,noDoublePaymentAfterReload:true,errors},null,2));console.log('PASS: distance changes service time, one-tile corridor, blocked aquarium, reopening.',JSON.stringify({near,far,narrow}));
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
