const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{const p=await browser.newPage({viewport:{width:1280,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.clock.install({time:new Date('2026-09-09T12:00:00Z')});await p.clock.pauseAt(new Date('2026-09-09T12:00:01Z'));
await p.goto('http://127.0.0.1:4174');await require('./test-start.cjs')(p);
await p.evaluate(()=>{Object.assign(state,{level:9,expansion:true,shelf:true,tank3:true,battery:true,employee:'eva',speed:1,identity:ShopIdentity.normalize({name:'El Jardín Acuático',icon:'plant',color:'terracotta',shape:'circle'})});state.stock=Object.fromEntries(Object.keys(products).map(k=>[k,20]));const l=ShopLayout.create();l.objects.forEach(o=>{if(['shelf','tank3','battery'].includes(o.kind))o.placed=true});state.layout=ShopLayout.migrate(l,state);saveGame(false)});await p.reload();await p.clock.runFor(24000);
const species=await p.locator('#furnitureLayer [data-species]').evaluateAll(nodes=>[...new Set(nodes.map(n=>n.dataset.species))]);assert.equal(species.length,8);
await p.screenshot({path:__dirname+'/v08-stocked-desktop.png',fullPage:true});await p.setViewportSize({width:390,height:844});await p.screenshot({path:__dirname+'/v08-stocked-mobile.png',fullPage:true});
// Visual contact sheet at useful inspection size, built only in this isolated test page.
await p.evaluate(()=>{const gallery=document.createElement('div');gallery.id='artContact';gallery.style='background:#fff6e4;padding:24px;width:900px;display:grid;grid-template-columns:repeat(4,1fr);gap:12px';
for(const key of Object.keys(ShopFish.catalog)){const item=document.createElement('div');item.innerHTML='<svg width="200" height="120" viewBox="-45 -30 90 60">'+ShopFish.fish(key)+'</svg><p>'+products[key].name+'</p>';gallery.append(item)}
for(let i=1;i<=8;i++){const item=document.createElement('div'),svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('width','200');svg.setAttribute('height','160');svg.setAttribute('viewBox','-45 -105 90 115');const node=ShopCharacters.create({id:i});ShopCharacters.update(node,{feet:{x:0,y:0},phase:i%2?'browsing':'leaving',moving:false,distance:0,facing:1,bubble:'',label:'',result:i%2?'pending':'sale'});node.querySelector('.visitor-bubble').remove();svg.append(node);item.append(svg);gallery.append(item)}document.body.replaceChildren(gallery)});
await p.setViewportSize({width:1000,height:1000});await p.locator('#artContact').screenshot({path:__dirname+'/v08-art-contact.png'});
assert.deepEqual(errors,[]);console.log('PASS: eight stocked species in the actual shop, both staff, mobile/desktop, visual contact sheet');}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
